# Generated by Django 4.0.2 on 2022-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insides', '0002_rename_id_authors_author_id_remove_books_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
