# Generated by Django 4.0.2 on 2022-04-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insides', '0002_delete_book_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insides.books'),
        ),
    ]
