# Generated by Django 4.0.2 on 2022-03-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insides', '0003_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
