# Generated by Django 4.0.2 on 2022-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insides', '0004_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
