# Generated by Django 4.0.2 on 2022-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insides', '0004_authr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
        migrations.AddField(
            model_name='authors',
            name='sc',
            field=models.ManyToManyField(to='insides.Books'),
        ),
    ]
